In [33]:
import pandas as pd

# pop_states_million

In [34]:
pop_states_pd = pd.read_csv("pop_states.csv")
pop_states_pd["n_killed_millon"] = pop_states_pd["n_killed"]*1000000/pop_states_pd["POPESTIMATE2019"]
pop_states_pd

,Unnamed: 0,state,n_killed,n_injured,POPESTIMATE2019,lat,long,n_killed_millon
0,0,Alabama,1880,2998,4903185,32.377716,-86.300568,383.424244
1,1,Alaska,267,325,731545,58.301598,-134.420212,364.980965
2,2,Arizona,1094,1096,7278717,33.448143,-112.096962,150.301214
3,3,Arkansas,773,1347,3017804,34.746613,-92.288986,256.146522
4,4,California,5562,7644,39512223,38.576668,-121.493629,140.766567
5,5,Colorado,796,1133,5758736,39.739227,-104.984856,138.224777
6,6,Connecticut,341,1258,3565287,41.764046,-72.682198,95.644474
7,7,Delaware,217,853,973764,39.157307,-75.519722,222.846603
8,8,District of Columbia,459,1415,705749,38.895110,-77.036370,650.372866
9,9,Florida,3909,7072,21477737,30.438118,-84.281296,182.002415
10,10,Georgia,2456,4056,10617423,33.749027,-84.388229,231.317901
11,11,Hawaii,63,85,1415872,21.307442,-157.857376,44.495548
12,12,Idaho,166,149,1787065,43.617775,-116.199722,92.889738
13,13,Illinois,3409,13514,12671821,39.798363,-89.654961,269.022108
14,14,Indiana,1608,2956,6732219,39.768623,-86.162643,238.851410
15,15,Iowa,273,821,3155070,41.591087,-93.603729,86.527399
16,16,Kansas,542,931,2913314,39.048191,-95.677956,186.042425
17,17,Kentucky,1066,1894,4467673,38.186722,-84.875374,238.602960
18,18,Louisiana,2179,4398,4648794,30.457069,-91.187393,468.723716
19,19,Maine,112,132,1344212,44.307167,-69.781693,83.320191
20,20,Maryland,1691,3167,6045680,38.978764,-76.490936,279.703855
21,21,Massachusetts,472,1701,6892503,42.358162,-71.063698,68.480202
22,22,Michigan,1588,2990,9986857,42.733635,-84.555328,159.008986
23,23,Minnesota,461,916,5639632,44.955097,-93.102211,81.742922
24,24,Mississippi,1176,1883,2976149,32.303848,-90.182106,395.141507
25,25,Missouri,2136,3585,6137428,38.579201,-92.172935,348.028523
26,26,Montana,154,136,1068778,46.585709,-112.018417,144.089792
27,27,Nebraska,225,674,1934408,40.808075,-96.699654,116.314655
28,28,Nevada,799,951,3080156,39.163914,-119.766121,259.402446
29,29,New Hampshire,88,144,1359711,43.206898,-71.537994,64.719635
30,30,New Jersey,1168,2540,8882190,40.220596,-74.769913,131.499101
31,31,New Mexico,495,543,2096829,35.682240,-105.939728,236.070753
32,32,New York,1705,5059,19453561,42.652843,-73.757874,87.644622
33,33,North Carolina,2225,4629,10488084,35.780430,-78.639099,212.145517
34,34,North Dakota,69,130,762062,46.820850,-100.783318,90.543814
35,35,Ohio,2508,5703,11689100,39.961346,-82.999069,214.558863
36,36,Oklahoma,941,1550,3956971,35.492207,-97.503342,237.808162
37,37,Oregon,446,694,4217737,44.938461,-123.030403,105.743910
38,38,Pennsylvania,2395,5056,12801989,40.264378,-76.883598,187.080304
39,39,Rhode Island,63,346,1059361,41.830914,-71.414963,59.469812
40,40,South Carolina,1610,3084,5148714,34.000343,-81.033211,312.699443
41,41,South Dakota,90,114,884659,44.367031,-100.346405,101.734115
42,42,Tennessee,1824,4478,6829174,36.165810,-86.784241,267.089402
43,43,Texas,5046,6106,28995881,30.274670,-97.740349,174.024718
44,44,Utah,282,402,3205958,40.777477,-111.888237,87.961227
45,45,Vermont,57,73,623989,44.262436,-72.580536,91.347764
46,46,Virginia,1459,3566,8535519,37.538857,-77.433640,170.932781
47,47,Washington,853,1287,7614893,47.035805,-122.905014,112.017332
48,48,West Virginia,335,649,1792147,38.336246,-81.612328,186.926630
49,49,Wisconsin,862,2117,5822434,43.074684,-89.384445,148.048050
50,50,Wyoming,73,52,578759,41.140259,-104.820236,126.131948

In [35]:
pop_states_pd.corr()

,Unnamed: 0,n_killed,n_injured,POPESTIMATE2019,lat,long,n_killed_millon
Unnamed: 0,1.000000,-0.116436,-0.102125,-0.070096,0.151380,0.128912,-0.281720
n_killed,-0.116436,1.000000,0.867922,0.907891,-0.403756,0.076061,0.237561
n_injured,-0.102125,0.867922,1.000000,0.734033,-0.298137,0.205440,0.252695
POPESTIMATE2019,-0.070096,0.907891,0.734033,1.000000,-0.244167,0.013679,-0.057696
lat,0.151380,-0.403756,-0.298137,-0.244167,1.000000,0.008425,-0.250644
long,0.128912,0.076061,0.205440,0.013679,0.008425,1.000000,0.111411
n_killed_millon,-0.281720,0.237561,0.252695,-0.057696,-0.250644,0.111411,1.000000

In [36]:
print("media:", pop_states_pd["n_killed_millon"].mean())
print("median:", pop_states_pd["n_killed_millon"].median())

media: 191.81597710919837
median: 170.93278100605247

In [37]:
pop_states_pd.to_csv("pop_states_millon.csv")

# ownership_data

In [30]:
ownership_HFR_pd = pd.read_csv("ownership.csv", sep=";")
ownership_HFR_pd["HFR"] = ownership_HFR_pd["HFR"].str.replace(",", ".").astype("float")
ownership_HFR_pd = ownership_HFR_pd[ownership_HFR_pd["Year"]>=2013][["STATE", "HFR"]].groupby("STATE").mean().reset_index()
ownership_HFR_pd

             STATE      HFR
0          Alabama  0.51225
1           Alaska  0.57925
2          Arizona  0.36775
3         Arkansas  0.49325
4       California  0.16300
5         Colorado  0.38175
6      Connecticut  0.18025
7         Delaware  0.32425
8          Florida  0.28200
9          Georgia  0.37475
10          Hawaii  0.07350
11           Idaho  0.53975
12        Illinois  0.23650
13         Indiana  0.41200
14            Iowa  0.36925
15          Kansas  0.41775
16        Kentucky  0.48850
17       Louisiana  0.48675
18           Maine  0.45225
19        Maryland  0.19175
20   Massachusetts  0.09075
21        Michigan  0.36350
22       Minnesota  0.37725
23     Mississippi  0.50125
24        Missouri  0.49975
25         Montana  0.63275
26        Nebraska  0.38100
27          Nevada  0.33800
28   New Hampshire  0.40550
29      New Jersey  0.08075
30      New Mexico  0.39175
31        New York  0.12850
32  North Carolina  0.34400
33    North Dakota  0.54350
34            Ohio  0.38300
35        Oklahoma  0.51650
36          Oregon  0.43475
37    Pennsylvania  0.37475
38    Rhode Island  0.12000
39  South Carolina  0.42700
40    South Dakota  0.51625
41       Tennessee  0.44525
42           Texas  0.36000
43            Utah  0.38025
44         Vermont  0.46325
45        Virginia  0.35750
46      Washington  0.32950
47   West Virginia  0.57150
48       Wisconsin  0.44675
49         Wyoming  0.59425

In [31]:
ownership_GFI_pd = pd.read_csv("ownership.csv", sep=";")
ownership_GFI_pd["GFI"] = ownership_GFI_pd["GFI"].str.replace(",", ".").astype("float")
ownership_GFI_pd = ownership_GFI_pd[ownership_GFI_pd["Year"]>=2013][["STATE", "GFI"]].groupby("STATE").mean().reset_index()
ownership_GFI_pd

             STATE     GFI
0          Alabama   96.14
1           Alaska  122.90
2          Arizona  119.26
3         Arkansas   81.12
4       California   24.06
5         Colorado   57.01
6      Connecticut   27.29
7         Delaware   53.87
8          Florida   71.30
9          Georgia   84.67
10          Hawaii   27.59
11           Idaho  110.22
12        Illinois   72.73
13         Indiana   87.17
14            Iowa   80.58
15          Kansas  104.81
16        Kentucky  108.83
17       Louisiana   67.57
18           Maine   43.74
19        Maryland   30.22
20   Massachusetts   20.61
21        Michigan   90.98
22       Minnesota   68.05
23     Mississippi   94.49
24        Missouri  104.79
25         Montana  115.26
26        Nebraska   76.53
27          Nevada   93.11
28   New Hampshire   94.58
29      New Jersey   24.18
30      New Mexico   87.75
31        New York   10.70
32  North Carolina   69.65
33    North Dakota   97.22
34            Ohio   70.85
35        Oklahoma  108.85
36          Oregon   61.30
37    Pennsylvania   75.86
38    Rhode Island   29.58
39  South Carolina   63.53
40    South Dakota  102.90
41       Tennessee   95.47
42           Texas  103.68
43            Utah   98.42
44         Vermont   81.69
45        Virginia   59.65
46      Washington   33.37
47   West Virginia   97.36
48       Wisconsin   66.04
49         Wyoming  117.08

In [38]:
data_pd = pd.read_csv("data.csv")
data_pd = data_pd[["state", "incident_id"]].groupby("state").nunique()
data_pd = data_pd.reset_index().rename(columns={"state":"STATE"})
data_pd

                   STATE  incident_id
0                Alabama         1490
1                 Alaska          624
2                Arizona          876
3               Arkansas         1097
4             California         5923
5               Colorado         1029
6            Connecticut         1305
7               Delaware          761
8   District of Columbia          370
9                Florida         5185
10               Georgia         2875
11                Hawaii          150
12                 Idaho          349
13              Illinois         9339
14               Indiana         2480
15                  Iowa         1233
16                Kansas          783
17              Kentucky         1400
18             Louisiana         2779
19                 Maine          509
20              Maryland         2611
21         Massachusetts         2970
22              Michigan         2529
23             Minnesota          828
24           Mississippi         1063
25              Missouri         2497
26               Montana          310
27              Nebraska          668
28                Nevada          531
29         New Hampshire          494
30            New Jersey         2406
31            New Mexico          575
32              New York         4372
33        North Carolina         2745
34          North Dakota          275
35                  Ohio         4358
36              Oklahoma         1073
37                Oregon         1067
38          Pennsylvania         3704
39          Rhode Island          451
40        South Carolina         1970
41          South Dakota          221
42             Tennessee         2244
43                 Texas         4426
44                  Utah          477
45               Vermont          194
46              Virginia         1856
47            Washington         1537
48         West Virginia          593
49             Wisconsin         1728
50               Wyoming          306

In [39]:
data_pd = data_pd.merge(ownership_HFR_pd, on=["STATE"])
data_pd = data_pd.merge(ownership_GFI_pd, on=["STATE"])
data_pd

             STATE  incident_id      HFR     GFI
0          Alabama         1490  0.51225   96.14
1           Alaska          624  0.57925  122.90
2          Arizona          876  0.36775  119.26
3         Arkansas         1097  0.49325   81.12
4       California         5923  0.16300   24.06
5         Colorado         1029  0.38175   57.01
6      Connecticut         1305  0.18025   27.29
7         Delaware          761  0.32425   53.87
8          Florida         5185  0.28200   71.30
9          Georgia         2875  0.37475   84.67
10          Hawaii          150  0.07350   27.59
11           Idaho          349  0.53975  110.22
12        Illinois         9339  0.23650   72.73
13         Indiana         2480  0.41200   87.17
14            Iowa         1233  0.36925   80.58
15          Kansas          783  0.41775  104.81
16        Kentucky         1400  0.48850  108.83
17       Louisiana         2779  0.48675   67.57
18           Maine          509  0.45225   43.74
19        Maryland         2611  0.19175   30.22
20   Massachusetts         2970  0.09075   20.61
21        Michigan         2529  0.36350   90.98
22       Minnesota          828  0.37725   68.05
23     Mississippi         1063  0.50125   94.49
24        Missouri         2497  0.49975  104.79
25         Montana          310  0.63275  115.26
26        Nebraska          668  0.38100   76.53
27          Nevada          531  0.33800   93.11
28   New Hampshire          494  0.40550   94.58
29      New Jersey         2406  0.08075   24.18
30      New Mexico          575  0.39175   87.75
31        New York         4372  0.12850   10.70
32  North Carolina         2745  0.34400   69.65
33    North Dakota          275  0.54350   97.22
34            Ohio         4358  0.38300   70.85
35        Oklahoma         1073  0.51650  108.85
36          Oregon         1067  0.43475   61.30
37    Pennsylvania         3704  0.37475   75.86
38    Rhode Island          451  0.12000   29.58
39  South Carolina         1970  0.42700   63.53
40    South Dakota          221  0.51625  102.90
41       Tennessee         2244  0.44525   95.47
42           Texas         4426  0.36000  103.68
43            Utah          477  0.38025   98.42
44         Vermont          194  0.46325   81.69
45        Virginia         1856  0.35750   59.65
46      Washington         1537  0.32950   33.37
47   West Virginia          593  0.57150   97.36
48       Wisconsin         1728  0.44675   66.04
49         Wyoming          306  0.59425  117.08

In [40]:
data_pd.corr()

             incident_id       HFR       GFI
incident_id     1.000000 -0.410267 -0.283371
HFR            -0.410267  1.000000  0.820692
GFI            -0.283371  0.820692  1.000000

In [41]:
data_pd.to_csv("ownership_data.csv")